name: Approval
run-name: Approval [${{ github.run_id }}-${{ github.run_attempt }}]
on:
  workflow_dispatch:
jobs:
  j1:
    environment: Approval
    runs-on: ubuntu-latest
    steps:
      - name: s1
        run: sleep 15 && echo "Approval received!"
