name: Context
on:
  workflow_dispatch:
    inputs:
      environment-code:
        description: The environment code to deploy to.
        required: true
        type: choice
        options:
          - Env01
          - Env02
jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - name: Output Contexts
        run: |
          echo "::group::GITHUB"
          echo "GITHUB: ${{ toJson(github) }}"
          echo "::endgroup::"

          echo "::group::ENV"
          echo "ENV: ${{ toJson(env) }}"
          echo "::endgroup::"

          echo "::group::VARS"
          echo "VARS: ${{ toJson(vars) }}"
          echo "::endgroup::"

          echo "::group::JOB"
          echo "JOB: ${{ toJson(job) }}"
          echo "::endgroup::"

          echo "::group::STEPS"
          echo "STEPS: ${{ toJson(steps) }}"
          echo "::endgroup::"

          echo "::group::RUNNER"
          echo "RUNNER: ${{ toJson(runner) }}"
          echo "::endgroup::"

          echo "::group::SECRETS"
          echo "SECRETS: ${{ toJson(secrets) }}"
          echo "::endgroup::"

          echo "::group::INPUTS"
          echo "INPUTS: ${{ toJson(inputs) }}"
          echo "::endgroup::"
